services:
  lexnetictodobackend:
    container_name: lexnetictodobackend
    env_file:
      - ../todo-backend/.env
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    depends_on:
      - lexnetictododb

    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:lexnetictododb

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  lexnetictododb:
    container_name: lexnetictododb
    image: postgres:16
    restart: always
    env_file:
      - ../todo-backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    
    networks:
      - todobackend
    
    ports:
      - 5432:5432


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  todobackend:
